apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: payday-viewer
  namespace: payday
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
